export default {
	INVITE: 'https://discord.gg/RS69ssj',
	GITHUB: 'https://github.com/ventingforest/bot',
	MOMENT_FORMAT: 'ddd, MMM Do, YYYY h:mm A',

	COMPLIMENTS: [
		'good morning, sunshine ☀',
		'who needs coffee when you have your smile ☕',
		'go get \'em, Tiger 🐯',
		'take on the day you beautiful land mermaid you 💖',
		'you\'re more fun than bubble wrap 🎉',
		'you made someone smile today, I know it 😇',
		'if I could high five you... I would 🤗',
		'on a scale from 1 to 10, you\'re a 15 💖',
		'you are the fairest of them all 💖',
		'you\'re beautiful and amazing 💖',
		'you\'re sweet like bubble tea~ 🍵',
		'if you were a pie, you\'d be a cutie pie 🥧',
		'you’re stronger than you think 😤',
		'are you made of Copper and Tellurium? Because you\'re CuTe 💖',
		'if no one has told you today, you\'re beautiful 💖',
		'you\'re a star ⭐',
		'you\'re stellar ✨',
		'I need a map because I think I just got lost in your eyes... 🗺',
		'I was told to get some sunshine, I think they meant you ☀',
		'when you stand in a garden, I can\'t tell the difference between you and the flowers 💐',
		'cutie, I choose you! You used Adorableness, it was super effective 🎮',
		'I love you a latte ☕',
		'you warm my heart like a cup of hot cocoa! ☕',
		'you\'re as lovely as a lilac 💜',
		'you\'re as cute as a cat 😻',
		'out of the 100 billion stars in the Milky Way, you shine the brightest! ✨',
		'if a star fell every time you made me smile, the sky would be empty ☁',
		'heaven must be missing an angel 😇',
		'are you a bag of chips? Because you\'re a snack 😎',
		'did it hurt when you fell from the vending machine? Because you look like a snack 🤤',
		'you\'re breathtaking 😮',
		'you\'re a gift to those around you 🎁',
		'you light up the room 🔦',
		'you\'re like a ray of sunshine on a dreary day ☀',
		'you\'re making such a positive difference in the world 🌍',
		'you\'re even more beautiful on the inside than out 💖',
		'you\'re more helpful than you realise 🤗',
		'you are so special and amazing ✨',
		'you make my earf quake 🌍',
		'you\'re the uwu of my life ❤',
		'you uwu my tears away 😇',
	],
};