export default {
	INVITE: 'https://discord.gg/RS69ssj',
	MOMENT_FORMAT: 'ddd, MMM Do, YYYY h:mm A',
	BAN_APPEAL: 'https://forms.gle/EoUp6hxmNvuAJXJfA',
	BLANKFIELD: '\u200B',

	COMPLIMENTS: [
		'Good morning, sunshine ☀',
		'Who needs coffee when you have your smile ☕',
		'You\'re more fun than bubble wrap 🎉',
		'You made someone smile today, I know it 😇',
		'On a scale from 1 to 10, you\'re a 15 💖',
		'You are the fairest of them all 💖',
		'You\'re beautiful and amazing 💖',
		'You\'re sweet like bubble tea~ 🍵',
		'If you were a pie, you\'d be a cutie pie 🥧',
		'You’re stronger than you think 😤',
		'Are you made of Copper and Tellurium? Because you\'re CuTe 💖',
		'If no one has told you today, you\'re beautiful 💖',
		'You\'re a star ⭐',
		'You\'re stellar ✨',
		'I need a map because I think I just got lost in your eyes... 🗺',
		'I was told to get some sunshine, I think they meant you ☀',
		'I love you a latte ☕',
		'You warm my heart like a cup of hot cocoa! ☕',
		'Out of the 100 billion stars in the Milky Way, you shine the brightest! ✨',
		'If a star fell every time you made me smile, the sky would be empty ☁',
		'Heaven must be missing an angel 😇',
		'You\'re breathtaking 😮',
		'You\'re a gift to those around you 🎁',
		'You\'re like a ray of sunshine on a dreary day ☀',
		'You\'re making such a positive difference in the world 🌍',
		'You\'re more helpful than you realise 🤗',
	],
};
